export const ADD_FACULTY_REQUEST = "ADD_FACULTY_REQUEST"
export const ADD_FACULTY_SUCCESS = "ADD_FACULTY_SUCCESS"
export const ADD_FACULTY_FAIL = "ADD_FACULTY_FAIL"

export const UPDATE_FACULTY_REQUEST = "UPDATE_FACULTY_REQUEST"
export const UPDATE_FACULTY_SUCCESS = "UPDATE_FACULTY_SUCCESS"
export const UPDATE_FACULTY_FAIL = "UPDATE_FACULTY_FAIL"

export const FETCH_FACULTY_REQUEST = "FETCH_FACULTY_REQUEST"
export const FETCH_FACULTY_SUCCESS = "FETCH_FACULTY_SUCCESS"
export const FETCH_FACULTY_FAIL = "FETCH_FACULTY_FAIL"

export const FETCH_FACULTIES_REQUEST = "FETCH_FACULTIES_REQUEST"
export const FETCH_FACULTIES_SUCCESS = "FETCH_FACULTIES_SUCCESS"
export const FETCH_FACULTIES_FAIL = "FETCH_FACULTIES_FAIL"
