export const ADD_COURSE_REQUEST = "ADD_COURSE_REQUEST"
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS"
export const ADD_COURSE_FAIL = "ADD_COURSE_FAIL"

export const UPDATE_COURSE_REQUEST = "UPDATE_COURSE_REQUEST"
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS"
export const UPDATE_COURSE_FAIL = "UPDATE_COURSE_FAIL"

export const FETCH_COURSE_REQUEST = "FETCH_COURSE_REQUEST"
export const FETCH_COURSE_SUCCESS = "FETCH_COURSE_SUCCESS"
export const FETCH_COURSE_FAIL = "FETCH_COURSE_FAIL"

export const FETCH_COURSES_REQUEST = "FETCH_COURSES_REQUEST"
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS"
export const FETCH_COURSES_FAIL = "FETCH_COURSES_FAIL"
