export const GET_ATTENDANCE_REQUEST = "GET_ATTENDANCE_REQUEST"
export const GET_ATTENDANCE_SUCCESS = "GET_ATTENDANCE_SUCCESS"
export const GET_ATTENDANCE_FAIL = "GET_ATTENDANCE_FAIL"

export const GET_ATTENDANCES_REQUEST = "GET_ATTENDANCES_REQUEST"
export const GET_ATTENDANCES_SUCCESS = "GET_ATTENDANCES_SUCCESS"
export const GET_ATTENDANCES_FAIL = "GET_ATTENDANCES_FAIL"
