export const ADD_DEPARTMENT_REQUEST = "ADD_DEPARTMENT_REQUEST"
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS"
export const ADD_DEPARTMENT_FAIL = "ADD_DEPARTMENT_FAIL"

export const UPDATE_DEPARTMENT_REQUEST = "UPDATE_DEPARTMENT_REQUEST"
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS"
export const UPDATE_DEPARTMENT_FAIL = "UPDATE_DEPARTMENT_FAIL"

export const FETCH_DEPARTMENT_REQUEST = "FETCH_DEPARTMENT_REQUEST"
export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS"
export const FETCH_DEPARTMENT_FAIL = "FETCH_DEPARTMENT_FAIL"

export const FETCH_DEPARTMENTS_REQUEST = "FETCH_DEPARTMENTS_REQUEST"
export const FETCH_DEPARTMENTS_SUCCESS = "FETCH_DEPARTMENTS_SUCCESS"
export const FETCH_DEPARTMENTS_FAIL = "FETCH_DEPARTMENTS_FAIL"
