export const QRCODE_GENERATE_REQUEST = "QRCODE_GENERATE_REQUEST"
export const QRCODE_GENERATE_SUCCESS = "QRCODE_GENERATE_SUCCESS"
export const QRCODE_GENERATE_FAIL = "QRCODE_GENERATE_FAIL"
export const QRCODE_GENERATE_RESET = "QRCODE_GENERATE_RESET"
