export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST"
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS"
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL"
export const USER_REGISTRATION_RESET = "USER_REGISTRATION_RESET"

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL"

export const USER_ACTIVATE_REQUEST = "USER_ACTIVATE_REQUEST"
export const USER_ACTIVATE_SUCCESS = "USER_ACTIVATE_SUCCESS"
export const USER_ACTIVATE_FAIL = "USER_ACTIVATE_FAIL"

export const USER_DEACTIVATE_REQUEST = "USER_DEACTIVATE_REQUEST"
export const USER_DEACTIVATE_SUCCESS = "USER_DEACTIVATE_SUCCESS"
export const USER_DEACTIVATE_FAIL = "USER_DEACTIVATE_FAIL"
